# Generated by Django 2.0.2 on 2020-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='file1',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
