# Generated by Django 2.0.2 on 2020-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0002_cvmodel_file1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmodel',
            name='file1',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
