# Generated by Django 2.0.2 on 2020-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0004_auto_20200620_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='file2',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cvmodel',
            name='file1',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
