# Generated by Django 2.0.2 on 2020-06-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0006_auto_20200620_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmodel',
            name='file1',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
