# Generated by Django 2.0.2 on 2020-06-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0008_auto_20200621_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmodel',
            name='file1',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
